pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }

    options {
        timeout(time: 1, unit: 'HOURS') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    
    }
    parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')


    } 

    // Build
    stages {
        stage('Init') {
            steps {
                sh """
                    cd 01-vpc
                    terraform init -reconfigure
                """               
            }
        }
        stage('Plan') {
            steps {
                sh """
                    cd 01-vpc
                    terraform plan
                """ 
            }
        }
        stage('Deploy') {
            when {
                expression { 
                    params.action == 'apply'                
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
                // submitter "alice,bob"
                // parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                // }
            }
            steps {
                sh """
                    cd 01-vpc
                    terraform apply -auto-approve
                """
                }
            }
        
        }


    }
}